<a href="https://colab.research.google.com/github/ReemAlbluwi/Machine-Learning---T5/blob/main/SVD_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**SVD**

#import libraries

In [1]:
import numpy as np

#Load the tabular dataset :

dataset :


    [1, 2, 1, 0, 4],

    [2, 3, 4, 0, 2],

    [3, 1, 1, 0, 5],

    [4, 0, 2, 5, 0],

    [5, 4, 0, 1, 2]


In [3]:
data = np.array([
    [1, 2, 1, 0, 4],
    [2, 3, 4, 0, 2],
    [3, 1, 1, 0, 5],
    [4, 0, 2, 5, 0],
    [5, 4, 0, 1, 2]
])
print("Original Data:\n", data)

Original Data:
 [[1 2 1 0 4]
 [2 3 4 0 2]
 [3 1 1 0 5]
 [4 0 2 5 0]
 [5 4 0 1 2]]


#Perform Singular Value Decomposition (SVD)


In [4]:
U, S, VT = np.linalg.svd(data, full_matrices=False)
print("U matrix:\n", U)
print("Singular values:\n", S)
print("VT matrix:\n", VT)

U matrix:
 [[-0.35204034 -0.38841088  0.06858116 -0.24890107 -0.81151061]
 [-0.435757   -0.14720066  0.75454006  0.42674571  0.19236735]
 [-0.47547476 -0.33554973 -0.14101786 -0.59405958  0.5371567 ]
 [-0.3868273   0.84326881  0.15226099 -0.31661873 -0.12582336]
 [-0.5572      0.06142506 -0.61878629  0.55025644 -0.00874639]]
Singular values:
 [11.03193008  5.9744172   3.52502532  3.31230566  1.0980371 ]
VT matrix:
 [[-0.63300689 -0.42745253 -0.30313804 -0.22582961 -0.5231586 ]
 [ 0.33321061 -0.21897922  0.06256248  0.71601446 -0.56958583]
 [-0.37738163 -0.06110042  0.92204884  0.04043054 -0.04517901]
 [ 0.09275077  0.72137098  0.06967495 -0.3118182  -0.60740103]
 [ 0.58073519 -0.49520004  0.2217309  -0.58091226 -0.17578369]]


# Extract the singular values and vectors

In [5]:
print("U matrix shape:", U.shape)
print("Singular values shape:", S.shape)
print("VT matrix shape:", VT.shape)

U matrix shape: (5, 5)
Singular values shape: (5,)
VT matrix shape: (5, 5)


# Perform dimensionality reduction by selecting top k singular values and vectors


In [6]:
k = 2
U_k = U[:, :k]
S_k = np.diag(S[:k])
VT_k = VT[:k, :]

In [7]:
data_reduced = U_k @ S_k @ VT_k
print("Reduced Data:\n", data_reduced)

Reduced Data:
 [[ 1.68517423  2.16823828  1.03211446 -0.78448115  3.35352314]
 [ 2.74997839  2.2474459   1.40223771  0.45592685  3.01586488]
 [ 2.65238506  2.68115204  1.46466169 -0.25083665  3.88603508]
 [ 4.38005462  0.72090701  1.60881922  4.57102627 -0.63704194]
 [ 4.0133692   2.54718625  1.88634605  1.65093492  3.00682541]]


# Print the original and reduced datasets


In [8]:
print("Original Data:\n", data)
print("Reduced Data (k=2):\n", data_reduced)

Original Data:
 [[1 2 1 0 4]
 [2 3 4 0 2]
 [3 1 1 0 5]
 [4 0 2 5 0]
 [5 4 0 1 2]]
Reduced Data (k=2):
 [[ 1.68517423  2.16823828  1.03211446 -0.78448115  3.35352314]
 [ 2.74997839  2.2474459   1.40223771  0.45592685  3.01586488]
 [ 2.65238506  2.68115204  1.46466169 -0.25083665  3.88603508]
 [ 4.38005462  0.72090701  1.60881922  4.57102627 -0.63704194]
 [ 4.0133692   2.54718625  1.88634605  1.65093492  3.00682541]]


#**Well done :)**